import streamlit as st
import requests
from PIL import Image
from io import BytesIO

# Streamlit UI
st.title("🔬 AI Image Generation")
st.write("This application showcases AI-powered image generation using deep learning models.")

# Button to simulate image generation
if st.button("Generate Image ⚡"):
    try:
        st.write("🧠 Processing input through the model...")
        
        response = requests.get("https://cataas.com/cat", timeout=5)
        if response.status_code == 200:
            # Convert response to an image
            img = Image.open(BytesIO(response.content))
            st.image(img, caption="Generated Image", use_column_width=True)
            st.write("✅ Image successfully generated by the model.")
        else:
            st.error("⚠️ Failed to generate image. Try again!")

    except requests.exceptions.RequestException:
        st.error("⚠️ Network error. Please check your connection.")

